language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: xIGwsbk7X1QcvunI4F0E4nmjciVU1UigmLbXTOz3Og0IJ/OkGJmnYZ8AEsfM7xGCBgp8h+UNUd9Wajw2BseTQspp7CYmqhXm5oqQOqkvNclmXX4JU4MyQqQzCl2Av5r6/sWERds+cCJU0HWx6IjTD1luruW0UOswQre1GZ2bZGkBdYdvGWg+ABQQqXFMdZe0MYqOr6oCsljNmHa7uU6T9sAjJxa5FnaaY3CUBza2uA69R13Grt1xphkTaNQkV+Ukgeet3+8jpdLu/4BhCh3zIsFNuvVkHy1qtao0BSa2P3JQMGANhuKHege8WjflJMTzWQPe7ZrhB9ecPUx4uV4Z0KzXmmKaobkTwEEvzq4yv3uxyXrbllAafzeSQ2N3LL0IWIAORohViRJ83L2utWB9a0SdMN+3h+5vJNJskRCqtwFhXW9kZv9lqvjP5ONhgaGG4LFQtF4+qQvZLlj81qUhAoYCJ5PAN0AsZKYkSSJxwPWS/WhGU+Q9Z1N4Jgo9hstukySB/VoNBS+73aVCLBA+R6JMpBod509qxmr4L88F6DexJrOuQjKN3fpzVrIPUBh+UDL/YHE1pml1jT6++8cfoFG3pXHBVZfy3iNBM3MD/n95OrCSy2xLKsKMbPVegPBlE/Xs+D9A7GarFQdFeJ9eV3cLqCk0OSCTFo9HD1CWlys=
  app: etsfrontend
  on: master
